version: '3.4'

services:
  tictactoe.api:
    image: ${DOCKER_REGISTRY-}tictactoeapi
    build:
      context: .
      dockerfile: TicTacToe.Api/Dockerfile
    ports:
      - "8000:80"

  tictactoeapi-dapr:
    image: daprio/daprd:latest
    command: [
      "./daprd",
      "-app-id", "tictactoeapi",
      "-app-port", "80",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-placement-host-address", "placement:50005",
      "-components-path", "/components"
    ]
    volumes:
      - "./Components/:/components"
    depends_on:
      - tictactoe.api
    network_mode: "service:tictactoe.api"